# Funding options for the Solar Radiation Visualization Suite
# You can customize this file with your own funding platforms

# github: [yourusername]
# patreon: yourusername
# ko_fi: yourusername
# custom: ['https://www.buymeacoffee.com/yourusername']

# This is a template - uncomment and add your actual funding links if desired

